In [1]:
import time
import numpy as np


In [2]:

    def _softmax(x):
        """
        Inputs:
        x : (N, C), score before softmax

        Returns:
        softmax : (same shape with x), softmax distribution over axis-1

        Description:
        Given an input x, apply softmax funciton over axis-1.
        """
        softmax = None
        # ========================= EDIT HERE ========================
        exp_x=np.exp(x)
        softmax=exp_x/np.sum(exp_x)
        del exp_x
        # ============================================================
        return softmax
    

In [3]:
x=np.asarray([[1,2],[3,6]])

In [4]:
x.shape

(2, 2)

In [5]:
        softmax = np.zeros(x.shape)
        for i,_x in enumerate(x):
            _x=np.exp(_x)
            softmax[i]=_x/np.sum(_x)


In [6]:
softmax

array([[0.26894142, 0.73105858],
       [0.04742587, 0.95257413]])

In [7]:
_softmax(x)

array([[0.00626879, 0.01704033],
       [0.04632042, 0.93037047]])

In [8]:
for _x in x:
    print(_softmax(_x))

[0.26894142 0.73105858]
[0.04742587 0.95257413]


In [9]:
x = np.array([[1, 2, 1, 1],
            [2, 1, 3, 2], 
            [3, 1, 3, 4], 
            [4, 1, 5, 5], 
            [1, 7, 5, 5], 
            [1, 2, 5, 6], 
            [1, 6, 6, 6], 
            [1, 7, 7, 7]])


In [10]:
x.shape

(8, 4)

In [11]:
W=np.asarray([[3,2,7],[1,11,8],[4,22,1],[4,12,3]])

In [12]:
W.shape

(4, 3)

In [13]:
linear_mul.shape

NameError: name 'linear_mul' is not defined

In [14]:
        linear_mul = np.matmul(x,W)
        prob = _softmax(linear_mul)
        pred = np.argmax(prob,axis=1)


In [15]:
linear_mul

array([[ 13,  58,  27],
       [ 27, 105,  31],
       [ 38, 131,  44],
       [ 53, 189,  56],
       [ 50, 249,  83],
       [ 49, 206,  46],
       [ 57, 272,  79],
       [ 66, 317,  91]])

In [16]:
prob

array([[9.42925762e-133, 3.29404242e-113, 1.13396656e-126],
       [1.13396656e-126, 8.50295414e-093, 6.19124764e-125],
       [6.78952746e-122, 1.66427989e-081, 2.73909087e-119],
       [2.21950832e-115, 2.57220937e-056, 4.45800163e-114],
       [1.10502813e-116, 2.93748211e-030, 2.37187193e-102],
       [4.06517129e-117, 6.21315959e-049, 2.02392961e-118],
       [1.21181048e-113, 2.86251858e-020, 4.34423497e-104],
       [9.81940205e-110, 1.00000000e+000, 7.07045056e-099]])

In [17]:
pred.shape

(8,)

In [18]:
y=np.asarray([1,2,0,1,2,2,1])

In [58]:
y=np.asarray([[1,2,0,1,2,2,1],[1,2,0,1,2,2,1],[1,2,0,1,2,2,1]])

In [63]:
y_reciprocal = np.zeros_like(y,dtype=np.float)

In [64]:
for idx1, _y1 in enumerate(y):
    for idx2, _y2 in enumerate(y[idx1]):
        if(_y2!=0):
            y_reciprocal[idx1][idx2]=1/_y2            

In [67]:
y*y

array([[1, 4, 0, 1, 4, 4, 1],
       [1, 4, 0, 1, 4, 4, 1],
       [1, 4, 0, 1, 4, 4, 1]])

In [66]:
y_reciprocal

array([[1. , 0.5, 0. , 1. , 0.5, 0.5, 1. ],
       [1. , 0.5, 0. , 1. , 0.5, 0.5, 1. ],
       [1. , 0.5, 0. , 1. , 0.5, 0.5, 1. ]])

In [51]:
np.reciprocal(y)

c:\users\xogud\anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.
c:\users\xogud\anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([          1,           0, -2147483648,           1,           0,
                 0,           1], dtype=int32)

In [24]:
np.max(y)

2

In [23]:
y.shape[0]

7

In [47]:
y_one_hot = np.zeros((y.shape[0],np.max(y)+1))

In [48]:
y_one_hot.shape

(7, 3)

In [49]:
for idx,_y in enumerate(y):
    y_one_hot[idx][_y]=1

In [50]:
y_one_hot

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [68]:
y

array([[1, 2, 0, 1, 2, 2, 1],
       [1, 2, 0, 1, 2, 2, 1],
       [1, 2, 0, 1, 2, 2, 1]])

In [70]:
exp_y=np.exp(y)

In [72]:
exp_y

array([[2.71828183, 7.3890561 , 1.        , 2.71828183, 7.3890561 ,
        7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 1.        , 2.71828183, 7.3890561 ,
        7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 1.        , 2.71828183, 7.3890561 ,
        7.3890561 , 2.71828183]])

In [71]:
np.sum(exp_y,axis=1)

array([31.32201378, 31.32201378, 31.32201378])

In [73]:
y

array([[1, 2, 0, 1, 2, 2, 1],
       [1, 2, 0, 1, 2, 2, 1],
       [1, 2, 0, 1, 2, 2, 1]])

In [74]:
y/2

array([[0.5, 1. , 0. , 0.5, 1. , 1. , 0.5],
       [0.5, 1. , 0. , 0.5, 1. , 1. , 0.5],
       [0.5, 1. , 0. , 0.5, 1. , 1. , 0.5]])

In [75]:
np.sum(y/2)

13.5

In [76]:
num_data=1000
batch_size=3

In [77]:
        num_batches = int(np.ceil(num_data / batch_size))


In [83]:
num_batches

334

In [81]:
for idx in range(10):
    print(idx)

0
1
2
3
4
5
6
7
8
9


In [82]:
idx

9

In [79]:
for batch_num in range(num_batches):
    pass

In [84]:
batch_num

333

In [85]:
y

array([[1, 2, 0, 1, 2, 2, 1],
       [1, 2, 0, 1, 2, 2, 1],
       [1, 2, 0, 1, 2, 2, 1]])

In [87]:
a=np.asarray([1,2,3,4])

In [88]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])