In [1]:
import numpy as np

In [4]:
a=np.asarray([[1,-2],[3,4]])

In [7]:
mask=a<=0

In [8]:
mask

array([[False,  True],
       [False, False]])

In [13]:
a[np.logical_not(mask)]

array([1, 3, 4])

In [14]:
out=a

In [15]:
out

array([[ 1, -2],
       [ 3,  4]])

In [16]:
out[mask]=0

In [17]:
out

array([[1, 0],
       [3, 4]])

In [18]:
a

array([[1, 0],
       [3, 4]])

In [19]:
2/(1+np.exp(-2*a))-1

array([[0.76159416, 0.        ],
       [0.99505475, 0.9993293 ]])

In [20]:
b=np.asarray([1,2])

In [21]:
a

array([[1, 0],
       [3, 4]])

In [22]:
b

array([1, 2])

In [23]:
a+b

array([[2, 2],
       [4, 6]])